//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
}

public partial class Book
{
    public int BookID { get; set; }
    public string Title { get; set; }
    public int CategoryID { get; set; }
    public string ISBN { get; set; }
    public string Author { get; set; }
    public int Stock { get; set; }
    public decimal Price { get; set; }

    public virtual Book Book1 { get; set; }
    public virtual Book Book2 { get; set; }
}

public partial class Cart
{
    public string Username { get; set; }
    public int BookID { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
}

public partial class Category
{
    public int CategoryID { get; set; }
    public string Name { get; set; }
}

public partial class Discount
{
    public int discountID { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public decimal Discount1 { get; set; }
}

public partial class Order
{
    public int OrderID { get; set; }
    public string UserName { get; set; }
    public System.DateTime OrderDate { get; set; }
    public decimal TotalPrice { get; set; }

    public virtual Order Order1 { get; set; }
    public virtual Order Order2 { get; set; }
}

public partial class OrderDetail
{
    public int DetailsID { get; set; }
    public int OrderID { get; set; }
    public int BookID { get; set; }
    public int Quantity { get; set; }
}

public partial class User
{
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string Role { get; set; }
}
